### ISSUE TITLE
New rule: blueprint-disabled-button-with-tooltip

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint-blueprint#1]
If a `<Tooltip>` wraps a `<Button>` with a `disabled` prop (suggesting that the button could be disabled), recommend using an `<AnchorButton>` instead.

Rationale: due to a browser limitation, `<button disabled>` will eat all mouseout events, so the `Tooltip` will never be dismissed. Anchor buttons do not have this limitation.

**Comment by bonebizz21** [comment]
K

**Comment by adidahiya** [comment]
Closing in favor of https://github.com/palantir/blueprint/issues/4359
